services:
  univspider:
    build:
      context: ./backend
    image: univspider_img
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - ./backend/.env
    command: python main.py
    ports:
      - "420:80"
    networks:
      - app-network